# Generated by Django 2.1.1 on 2018-09-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_version', models.CharField(max_length=30, verbose_name='小版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='changeLog.Version')),
            ],
            options={
                'verbose_name': '小版本',
                'verbose_name_plural': '小版本',
            },
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='small_version',
        ),
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='changeLog.SmallVersion'),
        ),
    ]
