# Generated by Django 2.1.1 on 2018-09-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeLog', '0002_auto_20180925_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='changeLog.Version', verbose_name='版本号'),
        ),
    ]
