# Generated by Django 2.1.5 on 2020-07-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dwz',
            fields=[
                ('dwz_id', models.AutoField(primary_key=True, serialize=False)),
                ('dwz_long_url', models.TextField(verbose_name='长链接')),
                ('dwz_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='短链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短链接',
                'verbose_name_plural': '短链接',
            },
        ),
    ]
