# Generated by Django 2.1.5 on 2020-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENote',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('author', models.CharField(default='Emiya', max_length=100, verbose_name='作者')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('visit_num', models.IntegerField(default='0', verbose_name='浏览量')),
                ('comment_num', models.IntegerField(default='0', verbose_name='评论数')),
                ('hot', models.IntegerField(default=0, verbose_name='热度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_stick', models.IntegerField(choices=[(0, '未置顶'), (1, '置顶')], default=0, verbose_name='置顶')),
                ('is_display', models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示')),
            ],
            options={
                'verbose_name': 'e-note',
                'verbose_name_plural': 'e-note',
            },
        ),
    ]
