# Generated by Django 2.1.5 on 2020-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enote',
            name='path',
            field=models.TextField(default='', verbose_name='路径'),
        ),
    ]
