# Generated by Django 2.1.5 on 2020-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNote', '0002_enote_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enote',
            name='path',
            field=models.CharField(default='', max_length=300, verbose_name='路径'),
        ),
    ]
