# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.IntegerField(verbose_name='id')),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(default='emiya', max_length=100, verbose_name='作者')),
                ('date', models.DateTimeField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_display', models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=1, verbose_name='展示')),
                ('is_delete', models.IntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1)),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
            },
        ),
    ]
