# Generated by Django 2.1.1 on 2018-09-15 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='Emiya', max_length=50)),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(default='Emiya', max_length=100, verbose_name='作者')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='日期')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_display', models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, verbose_name='展示')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
            },
        ),
    ]
