# Generated by Django 2.1.1 on 2018-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='username',
            field=models.CharField(default='Emiya', max_length=50),
        ),
        migrations.AlterField(
            model_name='diary',
            name='author',
            field=models.CharField(default='Emiya', max_length=100, verbose_name='作者'),
        ),
    ]
