# Generated by Django 2.1.1 on 2018-09-19 15:01

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='test',
            field=diary.models.WeatherField(max_length=10, null=True, verbose_name='test'),
        ),
    ]
