# Generated by Django 2.1.1 on 2018-09-19 15:06

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='test',
            field=diary.models.WeatherField(max_length=100, null=True, verbose_name='test'),
        ),
    ]
