# Generated by Django 2.1.1 on 2018-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180929_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='stick',
            new_name='is_stick',
        ),
        migrations.AlterField(
            model_name='diary',
            name='is_display',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示'),
        ),
        migrations.AlterField(
            model_name='diarycomment',
            name='is_display',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示'),
        ),
    ]
