# Generated by Django 2.1.1 on 2018-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180913_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='short_content',
            field=models.TextField(default='1', verbose_name='缩略正文'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='is_display',
            field=models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, verbose_name='展示'),
        ),
    ]
