# Generated by Django 2.1.1 on 2018-09-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180921_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Diary', verbose_name='主题'),
        ),
    ]
