# Generated by Django 2.1.1 on 2018-09-19 15:08

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180919_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='test',
            field=diary.models.WeatherField(default='', max_length=100, verbose_name='test'),
        ),
    ]
