# Generated by Django 2.1.1 on 2018-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180913_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='date_weather',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(max_length=20, null=True, verbose_name='天气'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='short_content',
            field=models.TextField(null=True, verbose_name='缩略正文'),
        ),
    ]
