# Generated by Django 2.1.2 on 2018-11-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20181029_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='diary_img', verbose_name='动态图片')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Diary', verbose_name='正文')),
            ],
            options={
                'verbose_name': '动态图片',
                'verbose_name_plural': '动态图片',
            },
        ),
    ]
