# Generated by Django 2.1.1 on 2018-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20180921_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='stick',
            field=models.IntegerField(choices=[(0, '未置顶'), (1, '置顶')], default=0, verbose_name='置顶'),
        ),
    ]
