# Generated by Django 2.1.1 on 2018-09-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diary_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='test1',
        ),
    ]
