# Generated by Django 2.1.1 on 2018-09-19 17:46

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_diary_test1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.RemoveField(
            model_name='diary',
            name='test',
        ),
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=diary.models.WeatherField(default='', max_length=100, verbose_name='天气'),
        ),
    ]
