# Generated by Django 2.1.2 on 2018-11-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20181116_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='time',
            new_name='dateTime',
        ),
    ]
