# Generated by Django 2.1.1 on 2018-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作')),
                ('about', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('qq', models.CharField(blank=True, max_length=50, null=True, verbose_name='QQ')),
                ('e_mail', models.TextField(blank=True, null=True, verbose_name='邮箱')),
                ('microBlog', models.CharField(blank=True, max_length=50, null=True, verbose_name='微博')),
                ('weChat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信')),
                ('jike', models.CharField(blank=True, max_length=50, null=True, verbose_name='即刻')),
            ],
            options={
                'verbose_name': '个人中心',
                'verbose_name_plural': '个人中心',
            },
        ),
    ]
