# Generated by Django 2.1.1 on 2018-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0003_auto_20180926_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': '计划单', 'verbose_name_plural': '计划单'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='things',
            field=models.TextField(max_length=100, verbose_name='代办事项'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='完成时间'),
        ),
    ]
