# Generated by Django 2.1.1 on 2018-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0005_personalcenter_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcenter',
            name='website_icon',
            field=models.ImageField(default=1, upload_to='websiteIcon/website_icon.jpg', verbose_name='网站图标'),
            preserve_default=False,
        ),
    ]
