# Generated by Django 2.1.1 on 2018-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0006_personalcenter_website_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcenter',
            name='website_icon',
            field=models.ImageField(upload_to='websiteIcon', verbose_name='网站图标'),
        ),
    ]
