# Generated by Django 2.1.1 on 2018-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0007_auto_20181006_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(max_length=100, verbose_name='留言')),
                ('contact', models.CharField(max_length=50, verbose_name='联系方式')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '访客留言',
                'verbose_name_plural': '访客留言',
            },
        ),
    ]
