# Generated by Django 2.1.1 on 2018-10-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0008_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='massage',
            new_name='message',
        ),
    ]
