# Generated by Django 2.1.1 on 2018-10-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0009_auto_20181025_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式'),
        ),
    ]
