# Generated by Django 2.1.1 on 2018-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0010_auto_20181025_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人头像',
                'verbose_name_plural': '个人头像',
            },
        ),
        migrations.CreateModel(
            name='WebsiteIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_icon', models.ImageField(upload_to='websiteIcon', verbose_name='网站图标')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站图标',
                'verbose_name_plural': '网站图标',
            },
        ),
        migrations.RemoveField(
            model_name='personalcenter',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='personalcenter',
            name='website_icon',
        ),
    ]
