# Generated by Django 2.1.1 on 2018-10-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0011_auto_20181028_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(upload_to='avatar', verbose_name='个人头像'),
        ),
    ]
