# Generated by Django 2.1.2 on 2018-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0012_auto_20181028_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=200, verbose_name='个人签名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '个人签名',
                'verbose_name_plural': '个人签名',
            },
        ),
    ]
