# Generated by Django 2.1.2 on 2018-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalcenter', '0013_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherUserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='ip')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('is_error', models.IntegerField(default=0, verbose_name='error')),
                ('errorJson', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '天气访客',
                'verbose_name_plural': '天气访客',
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '建议反馈', 'verbose_name_plural': '建议反馈'},
        ),
    ]
