# Generated by Django 2.1.5 on 2020-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVocabulary',
            fields=[
                ('vocabulary_id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=100, verbose_name='英语')),
                ('chinese', models.CharField(max_length=100, verbose_name='中文')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计算机专业英语词汇',
                'verbose_name_plural': '计算机专业英语词汇',
            },
        ),
    ]
