# Generated by Django 2.1.5 on 2020-02-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodGoodStudy',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=100, verbose_name='昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习使我快乐',
                'verbose_name_plural': '学习使我快乐',
            },
        ),
    ]
