# Generated by Django 2.1.5 on 2019-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='images',
            field=models.TextField(default='', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='is_display',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示'),
        ),
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='visit_num',
            field=models.IntegerField(default='0', verbose_name='浏览量'),
        ),
    ]
