# Generated by Django 2.1.5 on 2019-09-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngaShadiaoImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgaShadiaoImage',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='标题')),
                ('author', models.CharField(default='kemiwjb', max_length=100, verbose_name='作者')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('time', models.CharField(default='', max_length=100, verbose_name='时间')),
                ('visit_num', models.IntegerField(default='0', verbose_name='浏览量')),
                ('images_num', models.IntegerField(default='0', verbose_name='图片数')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('is_display', models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'NGA沙雕图',
                'verbose_name_plural': 'NGA沙雕图',
            },
        ),
        migrations.CreateModel(
            name='NgaShadiaoImageContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_photo_name', models.CharField(max_length=200, verbose_name='云相册名称')),
                ('cloud_photo_domain', models.CharField(max_length=200, verbose_name='云相册域名')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('time', models.CharField(default='', max_length=100, verbose_name='时间')),
                ('content', models.TextField(verbose_name='正文')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('all_floor_num', models.IntegerField(verbose_name='总楼数')),
                ('is_display', models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ngaShadiaoImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngaShadiaoImage.NgaShadiaoImage', verbose_name='标题')),
            ],
            options={
                'verbose_name': 'NGA沙雕图正文',
                'verbose_name_plural': 'NGA沙雕图正文',
            },
        ),
        migrations.CreateModel(
            name='NgaShadiaoImageUpImgList',
            fields=[
                ('upImgList_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.TextField(default='', verbose_name='图片')),
                ('images_num', models.IntegerField(default=0, verbose_name='图片数')),
                ('is_upload', models.IntegerField(choices=[(0, '未上传'), (1, '已上传')], default=0, verbose_name='是否上传')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ngaShadiaoImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngaShadiaoImage.NgaShadiaoImage', verbose_name='标题')),
            ],
            options={
                'verbose_name': 'NGA沙雕图上传',
                'verbose_name_plural': 'NGA沙雕图上传',
            },
        ),
        migrations.CreateModel(
            name='NgaShadiaoImageVerification',
            fields=[
                ('verificationID', models.AutoField(primary_key=True, serialize=False)),
                ('verification', models.CharField(default='', max_length=100, verbose_name='验证码')),
                ('verificationKey', models.CharField(default='', max_length=100, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
