# Generated by Django 2.1.5 on 2019-08-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0002_auto_20190818_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngashadiaoimage',
            old_name='text',
            new_name='content',
        ),
    ]
