# Generated by Django 2.1.5 on 2019-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0003_auto_20190818_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='time',
            field=models.CharField(default='', max_length=100, verbose_name='时间'),
        ),
    ]
