# Generated by Django 2.1.5 on 2019-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0004_ngashadiaoimage_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgaShadiaoImageVerification',
            fields=[
                ('verificationID', models.AutoField(primary_key=True, serialize=False)),
                ('verification', models.CharField(default='', max_length=100, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
