# Generated by Django 2.1.5 on 2019-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0006_ngashadiaoimageverification_verificationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngashadiaoimageverification',
            name='verificationKey',
            field=models.CharField(default='', max_length=100, verbose_name='Key'),
        ),
    ]
