# Generated by Django 2.1.5 on 2019-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0007_auto_20190819_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='img_length',
            field=models.IntegerField(default=0, verbose_name='图片数'),
        ),
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='like_num',
            field=models.IntegerField(default='0', verbose_name='点赞数'),
        ),
    ]
