# Generated by Django 2.1.5 on 2019-08-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0008_auto_20190820_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgaShadiaoImageContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=100, verbose_name='时间')),
                ('content', models.TextField(verbose_name='正文')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('all_floor_num', models.IntegerField(verbose_name='总楼数')),
                ('images', models.TextField(default='', verbose_name='图片')),
                ('is_display', models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'NGA沙雕图正文',
                'verbose_name_plural': 'NGA沙雕图正文',
            },
        ),
        migrations.RemoveField(
            model_name='ngashadiaoimage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ngashadiaoimage',
            name='images',
        ),
        migrations.AddField(
            model_name='ngashadiaoimagecontent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngaShadiaoImage.NgaShadiaoImage', verbose_name='标题'),
        ),
    ]
