# Generated by Django 2.1.5 on 2019-08-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0009_auto_20190820_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgaShadiaoImageUpImgList',
            fields=[
                ('upImgList_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.TextField(default='', verbose_name='图片')),
                ('images_num', models.IntegerField(default=0, verbose_name='图片数')),
                ('is_upload', models.IntegerField(choices=[(0, '未上传'), (1, '已上传')], default=0, verbose_name='是否上传')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'NGA沙雕图上传',
                'verbose_name_plural': 'NGA沙雕图上传',
            },
        ),
        migrations.RenameField(
            model_name='ngashadiaoimagecontent',
            old_name='title',
            new_name='ngaShadiaoImage',
        ),
        migrations.RemoveField(
            model_name='ngashadiaoimage',
            name='img_length',
        ),
        migrations.RemoveField(
            model_name='ngashadiaoimagecontent',
            name='images',
        ),
        migrations.AddField(
            model_name='ngashadiaoimage',
            name='images_num',
            field=models.IntegerField(default='0', verbose_name='图片数'),
        ),
        migrations.AddField(
            model_name='ngashadiaoimageupimglist',
            name='ngaShadiaoImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngaShadiaoImage.NgaShadiaoImage', verbose_name='标题'),
        ),
    ]
