# Generated by Django 2.1.5 on 2019-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaShadiaoImage', '0010_auto_20190820_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngashadiaoimagecontent',
            name='url',
            field=models.CharField(default=1, max_length=200, verbose_name='链接'),
            preserve_default=False,
        ),
    ]
