# Generated by Django 2.1.1 on 2018-10-10 18:22

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeDiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('e_mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='评论')),
                ('comment_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='评论对象')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_display', models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, verbose_name='展示')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='CodeDiary',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('author', models.CharField(default='Emiya', max_length=100, verbose_name='作者')),
                ('date', diary.models.MyDateField(blank=True, default='1', max_length=100, null=True, verbose_name='日期')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stick', models.IntegerField(choices=[(0, '未置顶'), (1, '置顶')], default=0, verbose_name='置顶')),
                ('is_display', models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, verbose_name='展示')),
            ],
            options={
                'verbose_name': '代码',
                'verbose_name_plural': '代码',
            },
        ),
        migrations.AddField(
            model_name='codecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeDiary.CodeDiary', verbose_name='主题'),
        ),
    ]
