# Generated by Django 2.1.1 on 2018-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0003_auto_20181029_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codediary',
            name='title',
            field=models.CharField(default='这是一个标题', max_length=200, verbose_name='标题'),
        ),
    ]
