# Generated by Django 2.1.1 on 2018-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0004_auto_20181029_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codediary',
            name='title',
            field=models.CharField(blank=True, default='这是一个标题', max_length=200, null=True, verbose_name='标题'),
        ),
    ]
