# Generated by Django 2.1.1 on 2018-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0006_auto_20181029_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codediary',
            old_name='stick',
            new_name='is_stick',
        ),
        migrations.AlterField(
            model_name='codecomment',
            name='is_display',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示'),
        ),
        migrations.AlterField(
            model_name='codediary',
            name='is_display',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '显示')], default=1, verbose_name='展示'),
        ),
    ]
