# Generated by Django 2.1.2 on 2018-11-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0007_auto_20181029_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDiaryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='codeDiary_img', verbose_name='代码图片')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('codeDiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeDiary.CodeDiary', verbose_name='正文')),
            ],
            options={
                'verbose_name': '代码图片',
                'verbose_name_plural': '代码图片',
            },
        ),
    ]
