# Generated by Django 2.1.2 on 2018-11-16 14:19

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0009_codediary_visit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codediary',
            name='date',
            field=diary.models.MyDateField(blank=True, max_length=100, null=True, verbose_name='日期'),
        ),
    ]
