# Generated by Django 2.1.2 on 2018-11-16 19:40

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0010_auto_20181116_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='codediary',
            name='dateTime',
            field=diary.models.MyTimeField(blank=True, default=' ', max_length=100, null=True, verbose_name='时间'),
        ),
    ]
