# Generated by Django 2.1.2 on 2018-11-16 19:41

import diary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0011_codediary_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codediary',
            name='dateTime',
            field=diary.models.MyTimeField(blank=True, max_length=100, null=True, verbose_name='时间'),
        ),
    ]
