# Generated by Django 2.1.2 on 2018-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeDiary', '0012_auto_20181116_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, default='Emiya', max_length=50, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
            options={
                'verbose_name': '密码',
                'verbose_name_plural': '密码',
            },
        ),
    ]
