# Generated by Django 2.1.5 on 2019-01-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_app_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
