# Generated by Django 2.1.5 on 2019-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190124_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_url',
            field=models.CharField(max_length=100, verbose_name='连接'),
        ),
    ]
